language: node_js
cache: npm
install: npm install
script: npm test
before_deploy: npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: s3cmd sync --delete-removed --no-mime-magic --guess-mime-type -P -M -r public/ $S3_BUCKET && aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  on:
    repo: impactasaurus/landing
    branch: master
notifications:
    email:
        on_failure: always
