language: go
install: go get -v github.com/spf13/hugo
script:
  - hugo
  - python --version
  - sudo pip install s3cmd
  - s3cmd sync --delete-removed --no-mime-magic --guess-mime-type -P -M -r public/ s3://impact-marketing/
notifications:
    email:
        on_failure: always
