baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Impactasaurus"
theme = "stellar"
googleAnalytics = "UA-123-45"

[params]
name="Impactasaurus"
logo="logo.svg"
tagline="Demonstrate and Improve Your Social Impact"
subtitle="Impact Measurement for All"
description="It is becoming increasing important to <b>demonstrate</b> your social impact to trustees, investors, donors and other stakeholders. In doing so, organisations are more likely to continue obtaining support, in an ever more competitive sector.<br /><br />In addition, by measuring social impact, you can understand what areas need <b>improvement</b> and what changes will be most benefical. As the saying goes, 'If you can't measure it, you can't improve it'.<br /><br />Impact Measurement has long been an exclusive activity for larger organisations. <b>We are changing this</b>. We believe impact measurement should be practiced by all organisations benefiting society. <br /><br />No matter what your budget, what CRM you use or the size of your organisation, <b>start measuring your impact</b> with Impactasaurus"
