baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Impactasaurus"
theme = "stellar"
googleAnalytics = "UA-123-45"

[params]
name="Impactasaurus"
logo="logo.svg"
tagline="Demonstrate and Improve Your Social Impact"
subtitle="Impact Measurement for All"
description="Impact Measurement has long been an exclusive activity for larger organisations. <b>We are changing this</b>. We believe impact measurement should be practiced by all organisations benefiting society. <br />No matter what your budget, what CRM you use or the size of your organisation, start measuring your impact with Impactasaurus"
