baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Impactasaurus"
theme = "stellar"
googleAnalytics = "UA-123-45"

[params]
name="Impactasaurus"
logo="logo.svg"
tagline="Demonstrate and improve your social impact by measuring it"
subtitle="Impact Measurement for All"
description="Impact Measurement has long been an exclusive activity for larger organisations. We are changing this. We believe impact measurement should be practiced by all organisations benefiting society. No matter what your budget, what CRM you use or the size of your organisation, start measuring your impact with Impactasaurus"
